using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using BancosAPI.Dominio.Entidades;

namespace BancosAPI.Infra.Data.EntidadeConfig
{
    public class BancoEntidadeConfig : IEntityTypeConfiguration<BancoEntidade>
    {
        public void Configure(EntityTypeBuilder<BancoEntidade> builder)
        {

            //definir as propriedades, os campos da tabela
            //***************************************************************************************
            builder.Property(p => p.ID)
                   .HasColumnType("varchar(03)")
                   .IsRequired();
            builder.Property(p => p.Nome)
                   .HasColumnType("varchar(100)")
                   .IsRequired();
            builder.Property(p => p.Fantasia)
                   .HasColumnType("varchar(40)")
                   .IsRequired();
            builder.Property(p => p.EmpresaID)
                   .HasColumnType("varchar(03)");

            //definir a chave primaria 
            //***************************************************************************************
            builder.HasKey(p => p.ID); // chave composta HasKey(t => new { t.DepartmentID, t.Name });

            //quando criar a tebela inserir alguns dados
            //***************************************************************************************
            builder.HasData(new BancoEntidade { ID = "000", Nome = "NAO INFORMADO", Fantasia = "NAO INFORMADO", EmpresaID = "  " },
                            new BancoEntidade { ID = "001", Nome = "BANCO DO BRASIL S.A.", Fantasia = "BB S/A", EmpresaID = "  " },
                            new BancoEntidade { ID = "003", Nome = "BANCO DA AMAZÔNIA S.A.", Fantasia = "BANCO DA AMAZÔNIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "004", Nome = "BANCO DO NORDESTE DO BRASIL S.A.", Fantasia = "BANCO DO NORDESTE DO BRASIL S.", EmpresaID = "  " },
                            new BancoEntidade { ID = "007", Nome = "BANCO NACIONAL DESENV.ECONÔMICO E SOCIAL", Fantasia = "BNDES", EmpresaID = "  " },
                            new BancoEntidade { ID = "008", Nome = "BANCO SANTANDER MERIDIONAL S.A.", Fantasia = "BANCO SANTANDER MERIDIONAL S.A", EmpresaID = "  " },
                            new BancoEntidade { ID = "021", Nome = "BANCO DO ESTADO DO ESPÍRITO SANTO S.A.", Fantasia = "BANCO DO ESTADO DO ESPÍRITO SA", EmpresaID = "  " },
                            new BancoEntidade { ID = "022", Nome = "BANCO DE CREDITO REAL DE MINAS GERAIS", Fantasia = "BANCO DE CREDITO REAL DE MINAS", EmpresaID = "  " },
                            new BancoEntidade { ID = "023", Nome = "BANCO DE DESEN. DE MINAS GERAIS S.A.", Fantasia = "BANCO DE DESEN. DE MINAS GERAI", EmpresaID = "  " },
                            new BancoEntidade { ID = "024", Nome = "BANCO DE PERNAMBUCO S.A.-BANDEPE", Fantasia = "BANCO DE PERNAMBUCO S.A.-BANDE", EmpresaID = "  " },
                            new BancoEntidade { ID = "025", Nome = "BANCO ALFA S.A.", Fantasia = "BANCO ALFA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "027", Nome = "BANCO DO ESTADO DE SANTA CATARINA S.A.", Fantasia = "BANCO DO ESTADO DE SANTA CATAR", EmpresaID = "  " },
                            new BancoEntidade { ID = "029", Nome = "BANCO BANERJ S.A.", Fantasia = "BANCO BANERJ S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "030", Nome = "BANCO DA PARAIBA S.A.", Fantasia = "BANCO DA PARAIBA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "031", Nome = "BANCO BEG S.A.", Fantasia = "BANCO BEG S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "033", Nome = "Banco Santander Banespa S/A", Fantasia = "SANTANDER BANESPA S/A", EmpresaID = "  " },
                            new BancoEntidade { ID = "034", Nome = "BANCO DO ESTADO DO AMAZONAS S.A.", Fantasia = "BANCO DO ESTADO DO AMAZONAS S.", EmpresaID = "  " },
                            new BancoEntidade { ID = "035", Nome = "BANCO DO ESTADO DO CEARÁ S.A.", Fantasia = "BANCO DO ESTADO DO CEARÁ S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "036", Nome = "BANCO BEM S.A.", Fantasia = "BANCO BEM S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "037", Nome = "BANCO DO ESTADO DO PARÁ S.A.", Fantasia = "BANCO DO ESTADO DO PARÁ S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "038", Nome = "BANCO BANESTADO S.A.", Fantasia = "BANCO BANESTADO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "039", Nome = "BANCO DO ESTADO DO PIAUÍ S.A.", Fantasia = "BANCO DO ESTADO DO PIAUÍ S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "041", Nome = "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.", Fantasia = "BANCO DO ESTADO DO RIO GRANDE", EmpresaID = "  " },
                            new BancoEntidade { ID = "042", Nome = "BANCO J. SAFRA S.A.", Fantasia = "BANCO J. SAFRA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "044", Nome = "BANCO BVA S.A.", Fantasia = "BANCO BVA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "045", Nome = "BANCO OPPORTUNITY S.A.", Fantasia = "BANCO OPPORTUNITY S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "046", Nome = "BANCO REGIONAL DE DESEN.DO EXTREMO SUL", Fantasia = "BANCO REGIONAL DE DESEN.DO EXT", EmpresaID = "  " },
                            new BancoEntidade { ID = "047", Nome = "BANCO DO ESTADO DE SERGIPE S.A.", Fantasia = "BANCO DO ESTADO DE SERGIPE S.A", EmpresaID = "  " },
                            new BancoEntidade { ID = "048", Nome = "BANCO BEMGE S.A.", Fantasia = "BANCO BEMGE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "049", Nome = "BANCO DE DESEN. DO ESTADO DA BAHIA S.A.", Fantasia = "BANCO DE DESEN. DO ESTADO DA B", EmpresaID = "  " },
                            new BancoEntidade { ID = "051", Nome = "BANCO DE DESEN. DO ESPÍRITO SANTO S.A.", Fantasia = "BANCO DE DESEN. DO ESPÍRITO SA", EmpresaID = "  " },
                            new BancoEntidade { ID = "057", Nome = "BANCO DE DESEN.DO EST.SANTA CATARINA S.A.", Fantasia = "BANCO DE DESEN.DO EST.SANTA CA", EmpresaID = "  " },
                            new BancoEntidade { ID = "061", Nome = "BANCO ABB S.A.", Fantasia = "BANCO ABB S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "062", Nome = "BANCO 1.NET S.A.", Fantasia = "BANCO 1.NET S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "063", Nome = "BANCO IBI S.A.- BANCO MÚLTIPLO", Fantasia = "BANCO IBI S.A.- BANCO MÚLTIPLO", EmpresaID = "  " },
                            new BancoEntidade { ID = "064", Nome = "GOLDMAN SACHS DO BRASIL BANCO MÚLTIPLO AS", Fantasia = "GOLDMAN SACHS DO BRASIL BANCO", EmpresaID = "  " },
                            new BancoEntidade { ID = "065", Nome = "LEMON BANK BANCO MÚLTIPLO S.A.", Fantasia = "LEMON BANK BANCO MÚLTIPLO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "070", Nome = "BANCO DE BRASÍLIA S.A.", Fantasia = "BANCO DE BRASÍLIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "073", Nome = "BANCO POPULAR DO BRASIL", Fantasia = "BANCO POPULAR DO BRASIL", EmpresaID = "  " },
                            new BancoEntidade { ID = "104", Nome = "CAIXA ECONÔMICA FEDERAL", Fantasia = "CAIXA ECONÔMICA FEDERAL", EmpresaID = "  " },
                            new BancoEntidade { ID = "107", Nome = "BANCO BBM S.A.", Fantasia = "BANCO BBM S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "109", Nome = "BANCO CREDIBANCO S.A.", Fantasia = "BANCO CREDIBANCO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "116", Nome = "BANCO ÚNICO S.A.", Fantasia = "BANCO ÚNICO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "148", Nome = "BANK OF AMERICA BRASIL S.A.", Fantasia = "BANK OF AMERICA BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "151", Nome = "BANCO NOSSA CAIXA S.A.", Fantasia = "BANCO NOSSA CAIXA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "168", Nome = "BANCO CCF BRASIL S.A.", Fantasia = "BANCO CCF BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "175", Nome = "CONTINENTAL BANCO S.A.", Fantasia = "CONTINENTAL BANCO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "200", Nome = "BANCO FICRISA AXELRUD S.A.", Fantasia = "BANCO FICRISA AXELRUD S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "201", Nome = "BANCO AXIAL S.A.", Fantasia = "BANCO AXIAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "204", Nome = "AMERICAN EXPRESS BANK BRASIL BANCO MÚLTIP", Fantasia = "AMERICAN EXPRESS", EmpresaID = "  " },
                            new BancoEntidade { ID = "205", Nome = "BANCO SUL AMERICA S.A.", Fantasia = "BANCO SUL AMERICA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "208", Nome = "BANCO PACTUAL S.A.", Fantasia = "BANCO PACTUAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "210", Nome = "DRESDNER BANK LATEINAMERIKA AG", Fantasia = "DRESDNER BANK LATEINAMERIKA AG", EmpresaID = "  " },
                            new BancoEntidade { ID = "211", Nome = "BANCO SISTEMA S.A.", Fantasia = "BANCO SISTEMA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "212", Nome = "BANCO MATONE S.A.", Fantasia = "BANCO MATONE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "213", Nome = "BANCO ARBI S.A.", Fantasia = "BANCO ARBI S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "214", Nome = "BANCO DIBENS S.A.", Fantasia = "BANCO DIBENS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "215", Nome = "BANCO AMERICA DO SUL S.A.", Fantasia = "BANCO AMERICA DO SUL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "216", Nome = "BANCO REGIONAL MALCON S.A.COM.CRED.CONS.", Fantasia = "BANCO REGIONAL MALCON S.A.COM.", EmpresaID = "  " },
                            new BancoEntidade { ID = "217", Nome = "BANCO JOHN DEERE S.A.", Fantasia = "BANCO JOHN DEERE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "218", Nome = "BANCO BONSUCESSO S.A.", Fantasia = "BANCO BONSUCESSO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "219", Nome = "BANCO ZOGBI S.A.", Fantasia = "BANCO ZOGBI S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "220", Nome = "CREFISUL", Fantasia = "CREFISUL", EmpresaID = "  " },
                            new BancoEntidade { ID = "221", Nome = "BANCO FLEMING GRAPHUS S.A.", Fantasia = "BANCO FLEMING GRAPHUS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "222", Nome = "BANCO CREDIT LYONNAIS BRASIL S.A.", Fantasia = "BANCO CREDIT LYONNAIS BRASIL S", EmpresaID = "  " },
                            new BancoEntidade { ID = "224", Nome = "BANCO FIBRA S.A.", Fantasia = "BANCO FIBRA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "225", Nome = "BANCO BRASCAN S.A.", Fantasia = "BANCO BRASCAN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "228", Nome = "BANCO ICATU S.A.", Fantasia = "BANCO ICATU S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "229", Nome = "BANCO CRUZEIRO DO SUL S.A.", Fantasia = "BANCO CRUZEIRO DO SUL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "231", Nome = "BANCO BOAVISTA INTERATLANTICO S.A.", Fantasia = "BANCO BOAVISTA INTERATLANTICO", EmpresaID = "  " },
                            new BancoEntidade { ID = "232", Nome = "BANCO INTERPART S.A.", Fantasia = "BANCO INTERPART S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "233", Nome = "BANCO GE CAPITAL S.A.", Fantasia = "BANCO GE CAPITAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "235", Nome = "BANCO LIBERAL S.A.", Fantasia = "BANCO LIBERAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "237", Nome = "BANCO BRADESCO S.A.", Fantasia = "BANCO BRADESCO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "241", Nome = "BANCO CLASSICO S.A.", Fantasia = "BANCO CLASSICO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "242", Nome = "BANCO EUROINVEST S.A. EUROBANCO", Fantasia = "BANCO EUROINVEST S.A. EUROBANC", EmpresaID = "  " },
                            new BancoEntidade { ID = "243", Nome = "BANCO MULTISTOCK S.A.", Fantasia = "BANCO MULTISTOCK S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "244", Nome = "BANCO CIDADE S.A.", Fantasia = "BANCO CIDADE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "246", Nome = "BANCO ABC-BRASIL S.A.", Fantasia = "BANCO ABC-BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "247", Nome = "BANCO UBS S.A.", Fantasia = "BANCO UBS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "249", Nome = "BANCO INVESTCRED UNIBANCO S.A.", Fantasia = "BANCO INVESTCRED UNIBANCO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "250", Nome = "BANCO SCHAHIN S.A.", Fantasia = "BANCO SCHAHIN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "252", Nome = "BANCO FININVEST S.A.", Fantasia = "BANCO FININVEST S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "254", Nome = "PARANÁ BANCO S.A.", Fantasia = "PARANÁ BANCO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "258", Nome = "BANCO INDUSCRED S.A.", Fantasia = "BANCO INDUSCRED S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "262", Nome = "BANCO BOREAL S.A.", Fantasia = "BANCO BOREAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "263", Nome = "BANCO CACIQUE S.A.", Fantasia = "BANCO CACIQUE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "265", Nome = "BANCO FATOR S.A.", Fantasia = "BANCO FATOR S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "266", Nome = "BANCO CÉDULA S.A.", Fantasia = "BANCO CÉDULA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "277", Nome = "BANCO PLANIBANC S.A.", Fantasia = "BANCO PLANIBANC S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "291", Nome = "BANCO BCN S.A.", Fantasia = "BANCO BCN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "294", Nome = "BCR BANCO DE CREDITO REAL", Fantasia = "BCR BANCO DE CREDITO REAL", EmpresaID = "  " },
                            new BancoEntidade { ID = "300", Nome = "BANCO DE LA NACION ARGENTINA", Fantasia = "BANCO DE LA NACION ARGENTINA", EmpresaID = "  " },
                            new BancoEntidade { ID = "318", Nome = "BANCO BMG S.A.", Fantasia = "BANCO BMG S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "320", Nome = "BANCO INDUSTRIAL E COMERCIAL S.A.", Fantasia = "BANCO INDUSTRIAL E COMERCIAL S", EmpresaID = "  " },
                            new BancoEntidade { ID = "341", Nome = "BANCO ITAÚ S.A.", Fantasia = "BANCO ITAÚ S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "347", Nome = "BANCO SUDAMERIS BRASIL S.A.", Fantasia = "BANCO SUDAMERIS BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "351", Nome = "BANCO BOZANO SIMONSEN S.A.", Fantasia = "BANCO BOZANO SIMONSEN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "353", Nome = "BANCO SANTANDER BRASIL S.A.", Fantasia = "BANCO SANTANDER BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "356", Nome = "BANCO ABN AMRO REAL S.A.", Fantasia = "BANCO ABN AMRO REAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "366", Nome = "BANCO SOCIETE GENERALE BRASIL S.A.", Fantasia = "BANCO SOCIETE GENERALE BRASIL", EmpresaID = "  " },
                            new BancoEntidade { ID = "370", Nome = "BANCO WESTLB DO BRASIL S.A.", Fantasia = "BANCO WESTLB DO BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "375", Nome = "BANCO FENICIA S.A.", Fantasia = "BANCO FENICIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "376", Nome = "BANCO J.P. MORGAN S.A.", Fantasia = "BANCO J.P. MORGAN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "389", Nome = "BANCO MERCANTIL DO BRASIL S.A.", Fantasia = "BANCO MERCANTIL DO BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "392", Nome = "BANCO MERCANTIL DE SAO PAULO S.A.", Fantasia = "BANCO MERCANTIL DE SAO PAULO S", EmpresaID = "  " },
                            new BancoEntidade { ID = "394", Nome = "BANCO BMC S.A.", Fantasia = "BANCO BMC S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "399", Nome = "HSBC BANK BRASIL S.A. BANCO MÚLTIPLO", Fantasia = "HSBC BANK BRASIL S.A. BANCO MÚ", EmpresaID = "  " },
                            new BancoEntidade { ID = "409", Nome = "UNIBANCO UNIÃO DE BANCOS BRASILEIROS SA", Fantasia = "UNIBANCO UNIÃO DE BANCOS BRASI", EmpresaID = "  " },
                            new BancoEntidade { ID = "412", Nome = "BANCO CAPITAL S.A.", Fantasia = "BANCO CAPITAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "422", Nome = "BANCO SAFRA S.A.", Fantasia = "BANCO SAFRA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "453", Nome = "BANCO RURAL S.A.", Fantasia = "BANCO RURAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "456", Nome = "BANCO DE TOKYO-MITSUBISHI BRASIL S.A.", Fantasia = "BANCO DE TOKYO-MITSUBISHI BRAS", EmpresaID = "  " },
                            new BancoEntidade { ID = "464", Nome = "BANCO SUMITOMO MITSUI BRASILEIRO S.A.", Fantasia = "BANCO SUMITOMO MITSUI BRASILEI", EmpresaID = "  " },
                            new BancoEntidade { ID = "472", Nome = "LLOYDS TSB BANK PLC", Fantasia = "LLOYDS TSB BANK PLC", EmpresaID = "  " },
                            new BancoEntidade { ID = "479", Nome = "BANKBOSTON BANCO MÚLTIPLO S.A.", Fantasia = "BANKBOSTON BANCO MÚLTIPLO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "480", Nome = "BANCO WACHOVIA S.A.", Fantasia = "BANCO WACHOVIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "487", Nome = "DEUTSCHE BANK S.A. - BANCO ALEMÃO", Fantasia = "DEUTSCHE BANK S.A. - BANCO ALE", EmpresaID = "  " },
                            new BancoEntidade { ID = "488", Nome = "BANCO J.P.MORGAN S.A.", Fantasia = "BANCO J.P.MORGAN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "489", Nome = "BANCO FRANCES INTERNACIONAL (BRASIL) S.A.", Fantasia = "BANCO FRANCES INTERNACIONAL (B", EmpresaID = "  " },
                            new BancoEntidade { ID = "492", Nome = "ING BANK N.V.", Fantasia = "ING BANK N.V.", EmpresaID = "  " },
                            new BancoEntidade { ID = "493", Nome = "BANCO UNION BRASIL S.A.", Fantasia = "BANCO UNION BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "494", Nome = "BANCO DE LA REPUB. ORIENTAL DEL URUGUAY", Fantasia = "BANCO DE LA REPUB. ORIENTAL DE", EmpresaID = "  " },
                            new BancoEntidade { ID = "495", Nome = "BANCO DE LA PROVÍNCIA DE BUENOS AIRES", Fantasia = "BANCO DE LA PROVÍNCIA DE BUENO", EmpresaID = "  " },
                            new BancoEntidade { ID = "496", Nome = "ARGENTARIA CAJA W.BANCO HIPOTECARIO S.A.", Fantasia = "ARGENTARIA CAJA W.BANCO HIPOTE", EmpresaID = "  " },
                            new BancoEntidade { ID = "498", Nome = "CENTRO HISPANO BANCO", Fantasia = "CENTRO HISPANO BANCO", EmpresaID = "  " },
                            new BancoEntidade { ID = "501", Nome = "BANCO BRASILEIRO IRAQUIANO S.A.", Fantasia = "BANCO BRASILEIRO IRAQUIANO S.A", EmpresaID = "  " },
                            new BancoEntidade { ID = "502", Nome = "BANCO DE SANTANDER DE NEGOCIOS S.A.", Fantasia = "BANCO DE SANTANDER DE NEGOCIOS", EmpresaID = "  " },
                            new BancoEntidade { ID = "505", Nome = "BANCO CREDIT SUISSE FIRST BOSTON S.A.", Fantasia = "BANCO CREDIT SUISSE FIRST BOST", EmpresaID = "  " },
                            new BancoEntidade { ID = "600", Nome = "BANCO LUSO BRASILEIRO S.A.", Fantasia = "BANCO LUSO BRASILEIRO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "602", Nome = "BANCO PATENTE S.A.", Fantasia = "BANCO PATENTE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "604", Nome = "BANCO INDUSTRIAL DO BRASIL S.A.", Fantasia = "BANCO INDUSTRIAL DO BRASIL S.A", EmpresaID = "  " },
                            new BancoEntidade { ID = "607", Nome = "BANCO SANTOS NEVES S.A.", Fantasia = "BANCO SANTOS NEVES S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "610", Nome = "BANCO VR S.A.", Fantasia = "BANCO VR S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "611", Nome = "BANCO PAULISTA S.A.", Fantasia = "BANCO PAULISTA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "612", Nome = "BANCO GUANABARA S.A.", Fantasia = "BANCO GUANABARA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "613", Nome = "BANCO PECÚNIA S.A.", Fantasia = "BANCO PECÚNIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "618", Nome = "BANCO TENDENCIA S.A.", Fantasia = "BANCO TENDENCIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "623", Nome = "BANCO PANAMERICANO S.A.", Fantasia = "BANCO PANAMERICANO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "624", Nome = "BANCO GM S.A.", Fantasia = "BANCO GM S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "625", Nome = "BANCO ARAUCARIA S.A.", Fantasia = "BANCO ARAUCARIA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "626", Nome = "BANCO FICSA S.A.", Fantasia = "BANCO FICSA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "627", Nome = "BANCO DESTAK S.A.", Fantasia = "BANCO DESTAK S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "630", Nome = "BANCO INTERCAP S.A.", Fantasia = "BANCO INTERCAP S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "633", Nome = "BANCO RENDIMENTO S.A.", Fantasia = "BANCO RENDIMENTO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "634", Nome = "BANCO TRIÂNGULO S.A.", Fantasia = "BANCO TRIÂNGULO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "637", Nome = "BANCO SOFISA S.A.", Fantasia = "BANCO SOFISA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "638", Nome = "BANCO PROSPER S.A.", Fantasia = "BANCO PROSPER S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "643", Nome = "BANCO PINE S.A.", Fantasia = "BANCO PINE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "650", Nome = "BANCO PEBB S.A.", Fantasia = "BANCO PEBB S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "653", Nome = "BANCO INDUSVAL S.A.", Fantasia = "BANCO INDUSVAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "654", Nome = "BANCO A.J. RENNER S.A.", Fantasia = "BANCO A.J. RENNER S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "655", Nome = "BANCO VOTORANTIM S.A.", Fantasia = "BANCO VOTORANTIM S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "656", Nome = "BANCO MATRIX S.A.", Fantasia = "BANCO MATRIX S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "657", Nome = "BANCO TECNICORP S.A.", Fantasia = "BANCO TECNICORP S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "658", Nome = "BANCO PORTO REAL S.A.", Fantasia = "BANCO PORTO REAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "707", Nome = "BANCO DAYCOVAL S.A.", Fantasia = "BANCO DAYCOVAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "719", Nome = "BANIF BANCO INTERNACIONAL DO FUNCHAL BRAS", Fantasia = "BANIF BANCO INTERNACIONAL DO F", EmpresaID = "  " },
                            new BancoEntidade { ID = "720", Nome = "BANCO MAXINVEST S.A.", Fantasia = "BANCO MAXINVEST S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "721", Nome = "BANCO CREDIBEL S.A.", Fantasia = "BANCO CREDIBEL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "722", Nome = "BANCO INTERIOR DE SAO PAULO S.A.", Fantasia = "BANCO INTERIOR DE SAO PAULO S.", EmpresaID = "  " },
                            new BancoEntidade { ID = "725", Nome = "BANCO FINANSINOS S.A.", Fantasia = "BANCO FINANSINOS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "732", Nome = "BANCO MINAS S.A.", Fantasia = "BANCO MINAS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "733", Nome = "BANCO DAS NACOES S.A.", Fantasia = "BANCO DAS NACOES S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "734", Nome = "BANCO GERDAU S.A.", Fantasia = "BANCO GERDAU S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "735", Nome = "BANCO POTTENCIAL S.A.", Fantasia = "BANCO POTTENCIAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "737", Nome = "BANCO THECA S.A.", Fantasia = "BANCO THECA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "738", Nome = "BANCO MORADA S.A.", Fantasia = "BANCO MORADA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "739", Nome = "BANCO BGN S.A.", Fantasia = "BANCO BGN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "740", Nome = "BANCO BARCLAYS S.A.", Fantasia = "BANCO BARCLAYS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "741", Nome = "BANCO RIBEIRÃO PRETO S.A.", Fantasia = "BANCO RIBEIRÃO PRETO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "742", Nome = "BANCO EQUATORIAL S.A.", Fantasia = "BANCO EQUATORIAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "743", Nome = "BANCO EMBLEMA S.A.", Fantasia = "BANCO EMBLEMA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "745", Nome = "BANCO CITIBANK S.A.", Fantasia = "BANCO CITIBANK S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "746", Nome = "BANCO MODAL S.A.", Fantasia = "BANCO MODAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "747", Nome = "BANCO RABOBANK INTERNACIONAL BRASIL S.A.", Fantasia = "BANCO RABOBANK INTERNACIONAL B", EmpresaID = "  " },
                            new BancoEntidade { ID = "748", Nome = "BANCO COOPERATIVO SICREDI S.A.", Fantasia = "BANCO COOPERATIVO SICREDI S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "749", Nome = "BANCO SIMPLES S.A.", Fantasia = "BANCO SIMPLES S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "751", Nome = "DRESDNER BANK BRASIL S.A. BANCO MULTIPLO", Fantasia = "DRESDNER BANK BRASIL S.A. BANC", EmpresaID = "  " },
                            new BancoEntidade { ID = "752", Nome = "BANCO BNP PARIBAS BRASIL S.A.", Fantasia = "BANCO BNP PARIBAS BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "753", Nome = "BANCO COMERCIAL URUGUAI S.A.", Fantasia = "BANCO COMERCIAL URUGUAI S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "755", Nome = "BANCO MERRILL LYNCH S.A.", Fantasia = "BANCO MERRILL LYNCH S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "756", Nome = "BANCO COOPERATIVO DO BRASIL S.A.", Fantasia = "BANCO COOPERATIVO DO BRASIL S.", EmpresaID = "  " },
                            new BancoEntidade { ID = "757", Nome = "BANCO KEB DO BRASIL S.A.", Fantasia = "BANCO KEB DO BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "915", Nome = "BANCO BRJ S.A.", Fantasia = "BANCO BRJ S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "930", Nome = "BANCO CARGILL S.A.", Fantasia = "BANCO CARGILL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "932", Nome = "BANCO CNH CAPITAL S.A.", Fantasia = "BANCO CNH CAPITAL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "935", Nome = "BANCO DAIMLER-CHRYSLER S.A.", Fantasia = "BANCO DAIMLER-CHRYSLER S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "940", Nome = "BANCO FIAT S.A.", Fantasia = "BANCO FIAT S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "942", Nome = "BANCO FORD S.A.", Fantasia = "BANCO FORD S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "945", Nome = "BANCO HEXABANCO S.A.", Fantasia = "BANCO HEXABANCO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "950", Nome = "BANCO HONDA S.A.", Fantasia = "BANCO HONDA S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "957", Nome = "BANCO MONEO S.A.", Fantasia = "BANCO MONEO S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "960", Nome = "BANCO MORGAN STANLEY DEAN WITTER S.A.", Fantasia = "BANCO MORGAN STANLEY DEAN WITT", EmpresaID = "  " },
                            new BancoEntidade { ID = "972", Nome = "BANCO OURINVEST S.A.", Fantasia = "BANCO OURINVEST S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "976", Nome = "BANCO PERFORMANCE S.A.", Fantasia = "BANCO PERFORMANCE S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "978", Nome = "BANCO PSA FINANCE BRASIL S.A.", Fantasia = "BANCO PSA FINANCE BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "980", Nome = "BANCO RODOBENS S.A.", Fantasia = "BANCO RODOBENS S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "985", Nome = "BANCO TOYOTA DO BRASIL S.A.", Fantasia = "BANCO TOYOTA DO BRASIL S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "992", Nome = "BANCO TRICURY S.A.", Fantasia = "BANCO TRICURY S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "997", Nome = "BANCO VOLKSWAGEN S.A.", Fantasia = "BANCO VOLKSWAGEN S.A.", EmpresaID = "  " },
                            new BancoEntidade { ID = "998", Nome = "BANCO VOLVO BRASIL S.A.", Fantasia = "BANCO VOLVO BRASIL S.A.", EmpresaID = "  " });
        }
    }
}
