FROM mcr.microsoft.com/dotnet/aspnet:3.1-focal AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1-focal AS build
WORKDIR /source

# copy everything else and build app
COPY ./BancosApi/. ./BancosApi/
COPY ./BancosApi.Dominio/. ./BancosApi.Dominio/
COPY ./BancosApi.Infra.Data/. ./BancosApi.Infra.Data/
COPY ./BancosAPi.Infra.IC/. ./BancosAPi.Infra.IC/
COPY ./BancosApi.Servico/. ./BancosApi.Servico/

RUN dotnet restore "./BancosApi/BancosAPI.csproj"

COPY . ./
WORKDIR "/source/."
RUN dotnet build "./BancosApi/BancosAPI.csproj" -c Release -o /app/build

# FROM build AS publish
RUN dotnet publish "./BancosApi/BancosAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
# COPY --from=publish /app/publish .
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BancosAPI.dll"]

# atualizar o linux
# RUN apt-get update && apt-get upgrade -y